export const forms = {
  '.field + .field': {
    marginTop: '1.25rem',
  },
  '.input': {
    fontSize: '1rem',
    color: 'rgba(var(--glyph-gray))',
    position: 'relative',
    display: 'block',
    width: '100%',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    lineHeight: '1.25rem',
    backgroundColor: 'rgba(var(--fill))',
    borderWidth: 1,
    borderRadius: 6,
    appearance: 'none',
    '-webkit-appearance': 'none',
    paddingTop: 7,
    paddingBottom: 7,
  },
  '.input-sm': {
    fontSize: '0.75rem',
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    lineHeight: '1rem',
    paddingTop: 3,
    paddingBottom: 3,
  },
  '.input::placeholder': {
    color: 'rgba(var(--glyph-gray-tertiary))',
  },
  '.input:disabled': {
    opacity: '.4',
    backgroundColor: 'rgba(var(--fill-tertiary))',
    cursor: 'not-allowed',
  },
  '.input:focus': {
    borderColor: 'rgba(var(--fill-primary, var(--primary)))',
    boxShadow: '0 0 0 3px rgba(var(--fill-primary, var(--primary)), 0.5)',
    outline: '0',
  },
  '.input:read-only': {
    backgroundColor: 'rgba(var(--fill-tertiary))',
  },
  '.label': {
    color: 'rgba(var(--glyph-gray))',
    fontSize: '1rem',
    display: 'block',
    marginBottom: '0.25rem',
  },
  '.input.error': {
    borderColor: 'rgba(var(--fill-red))',
    backgroundColor: 'rgba(var(--fill-red-secondary))',
  },
  '.input.error:focus': {
    boxShadow: '0 0 0 3px rgba(227, 0, 0, 0.35)',
    outline: '0',
  },
  '.input-search': {
    position: 'relative',
  },
  '.input-search .input': {
    paddingLeft: '2.2rem',
  },
  '.input-search.input-search-sm .input': {
    fontSize: '0.75rem',
    paddingLeft: '1.8rem',
    paddingRight: '0.5rem',
    lineHeight: '1rem',
    paddingTop: 3,
    paddingBottom: 3,
    height: '1.5rem',
  },
  '.input-search::before': {
    fontFamily: '"SF Pro Icons"',
    fontSize: '1.25rem',
    lineHeight: 1,
    color: 'rgba(var(--glyph-gray-tertiary))',
    position: 'absolute',
    zIndex: '10',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    top: 11,
    left: 10,
    content: '""',
    pointerEvents: 'none',
  },
  '.input-search.input-search-sm::before': {
    fontSize: '1rem',
    top: 6,
    left: 8,
  },
  '.message': {
    color: 'rgba(var(--glyph-gray-secondary))',
    fontSize: '0.875rem',
    position: 'relative',
    display: 'block',
    paddingTop: '0.25rem',
    lineHeight: '1.25rem',
  },
  '.message::before': {
    fontSize: '0.875rem',
    fontFamily: '"SF Pro Icons"',
    zIndex: '50',
    display: 'inline-block',
    marginRight: '0.25rem',
    lineHeight: '1.25rem',
    content: '""',
  },
  '.message-error, .message-error::before': {
    color: 'rgba(var(--glyph-red))',
  },
  '.message-error::before': {
    content: '""',
  },
  '.control': {
    position: 'relative',
  },
  '.input-password': {
    paddingRight: '4rem',
  },
  '.show-password': {
    color: 'rgba(var(--glyph-primary, var(--primary)))',
    fontSize: '0.875rem',
    position: 'absolute',
    top: '0',
    bottom: '0',
    right: '0',
    display: 'flex',
    alignItems: 'center',
    paddingRight: '0.75rem',
    lineHeight: '1.25rem',
    cursor: 'pointer',
  },
  '.select': {
    position: 'relative',
  },
  '.select::after': {
    fontFamily: '"SF Pro Icons"',
    color: 'rgba(var(--glyph-gray-tertiary))',
    fontSize: '1.25rem',
    position: 'absolute',
    lineHeight: '1.5rem',
    content: '""',
    right: '0.5rem',
    top: '0.4rem',
    pointerEvents: 'none',
  },
  '.select .input': {
    display: 'block',
    width: '100%',
    paddingLeft: '0.75rem',
    paddingRight: '0.75rem',
    backgroundColor: 'rgba(var(--fill))',
    borderRadius: 6,
    appearance: 'none',
    '-webkit-appearance': 'none',
    paddingTop: 7,
    paddingBottom: 7,
  },
  '.select-sm .input': {
    fontSize: '0.75rem',
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    lineHeight: '1rem',
    paddingTop: 3,
    paddingBottom: 3,
  },
  '.select-sm::after': {
    right: '0.375rem',
    top: '0',
  },
  '.checkbox-group': {
    display: 'flex',
    flexDirection: 'column',
  },
  '.checkbox-group label + label': {
    marginTop: '0.75rem',
  },
  '.label + .checkbox, .label + .radio': {
    marginTop: '0.75rem',
  },
  '.checkbox, .radio': {
    display: 'inline-flex',
    alignItems: 'center',
    height: '1.25rem',
    cursor: 'pointer',
  },
  '.checkbox .label, .radio .label': {
    marginBottom: '0',
    marginLeft: '0.5rem',
  },
  '.checkbox input, .radio input': {
    cursor: 'pointer',
  },
  '.radio-option': {
    fontSize: '1rem',
    lineHeight: '1.5rem',
  },
  '.radio input[type="radio"]': {
    width: '1rem',
    height: '1rem',
    backgroundColor: 'rgba(var(--fill))',
    borderWidth: 1,
    borderRadius: 9999,
    boxShadow: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
    appearance: 'none',
    '-webkit-appearance': 'none',
  },
  '.radio input[type="radio"]:checked': {
    borderColor: 'rgba(var(--fill-primary, var(--primary)))',
    boxShadow: 'none',
    borderWidth: 6,
    background: '#fff',
  },
  '.checkbox input[type="checkbox"]': {
    width: '1rem',
    height: '1rem',
    backgroundColor: 'rgba(var(--fill))',
    borderWidth: 1,
    borderRadius: 4,
    boxShadow: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
    appearance: 'none',
    '-webkit-appearance': 'none',
  },
  '.checkbox input[type="checkbox"]:disabled, .checkbox input[type="checkbox"]:disabled:checked':
    {
      opacity: '.4',
      cursor: 'not-allowed',
    },
  '.checkbox input[type="checkbox"]:checked': {
    backgroundColor: 'rgba(var(--fill-primary, var(--primary)))',
    borderColor: 'rgba(var(--fill-primary, var(--primary)))',
    position: 'relative',
    boxShadow: 'none',
  },
  '.checkbox input[type="checkbox"]:checked::after': {
    fontFamily: '"SF Pro Icons"',
    fontSize: '0.875rem',
    position: 'absolute',
    display: 'block',
    width: '1rem',
    height: '1rem',
    fontWeight: '600',
    lineHeight: '1rem',
    textAlign: 'center',
    content: '""',
    color: '#fff',
    left: -1,
    top: -2,
  },
  '.checkbox input[type="checkbox"]:focus, .radio input[type="radio"]:focus': {
    boxShadow: '0 0 0 3px rgba(var(--fill-primary, var(--primary)), 0.35)',
    borderColor: 'rgba(var(--fill-primary, var(--primary)))',
    outline: '0',
  },
  '.radio input[type="radio"]:disabled, .radio input[type="radio"]:disabled:checked':
    {
      backgroundColor: 'rgba(var(--fill))',
      cursor: 'not-allowed',
    },
  '.radio input[type="radio"]:disabled:checked': {
    borderColor: 'rgba(var(--fill-gray-tertiary))',
  },
  '.checkbox input[type="checkbox"]:disabled:checked': {
    backgroundColor: 'rgba(var(--fill-gray-secondary))',
    borderColor: 'rgba(var(--fill-gray-secondary))',
  },
  '.checkbox.disabled, .radio.disabled': {
    cursor: 'not-allowed',
  },
  '.checkbox.disabled .label, .radio.disabled .label': {
    borderColor: 'rgba(var(--fill-gray-secondary))',
    color: 'rgba(var(--glyph-gray-tertiary))',
    cursor: 'not-allowed',
  },
};
